### PR TITLE
Implement repository path command line argument (#454)

### PR DESCRIPTION
**Pull request by kitroed**
RepositoryPath created as an optional parameter which is null by default.

Note that this is technically a partial implementation as the ScriptsRunErrorsTable also has a repository_path field which will remain unused, but this seems like a good start.

### CODE REVIEW

**Comment by kitroed** [comment]
I haven't used GitHub regularly in a while, is this PR working well enough to fix #454?

**Comment by erikbra** [comment]
Thanks a lot, @kitroed !

This looks all jiffy-jaffy, good stuff, except for one thing. As we also distribute grate as DLL/s nuget packages, we have to be extra careful when changing the interface of public types. And, since IDatabase is public, adding an (optional) parameter to the method, will break binary compatibility, and might cause problems for the users of the nuget packages. So, keeping strictly to semantic versioning, this is a breaking change, and would force a major version bump.

I see that the Microsoft .NET guidelines also says that adding a member to a public interface is to be considered a breaking change as well, because of the option to have default implementations in interfaces, but I choose to ignore this, and hope that it's OK.

https://learn.microsoft.com/en-us/dotnet/core/compatibility/library-change-rules#members

Could you please change adding the new, optional "repositoryPath" parameter with overloads that have the parameter (as required), so that we have pairs of methods, both with and without the repository path?

**Comment by erikbra** [comment]
FYI, @kitroed, I simplified setting the `repository_path` a bit, to avoid adding a separate parameter for it, and added it to the ScriptsRunErrors table too.

**Comment by erikbra** [comment]
No worries ☺️

Please wait for the 1.6.3 release in anticipation (it might be called 1.7.0, we'll see)

**Pull request merged**
